##python program to print all prime numbers in an interval

In [8]:

lower=int(input("enter a lower case: "))
upper=int(input("enter a upper case: "))
for num in range(lower,upper+1):
  if(num>1):
    for divisor in range (2,int(num/2)+1):
      if num % divisor == 0:
        break
    else:
       print(num,"is prime")

enter a lower case: 1
enter a upper case: 20
2 is prime
3 is prime
5 is prime
7 is prime
11 is prime
13 is prime
17 is prime
19 is prime

##display the multiplication table

In [9]:

n=int(input("enter a number: "))
start=int(input("enter a first value: "))
end=int(input("enter a second value: "))
for i in range(start,end+1):
  print(n,"x",i,"=",n*i)

enter a number: 4
enter a first value: 1
enter a second value: 10
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40